// <auto-generated />
using System;
using Hospital_Management_System.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.DataAccess.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20240718085455_skdksdka")]
    partial class skdksdka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.DataAccess.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System.DataAccess.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Password = "admin123",
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            HospitalId = 1,
                            IsDeleted = false,
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            HospitalId = 1,
                            IsDeleted = false,
                            PatientId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            HospitalId = 1,
                            IsDeleted = false,
                            PatientId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            HospitalId = 1,
                            IsDeleted = false,
                            PatientId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            HospitalId = 1,
                            IsDeleted = false,
                            PatientId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            HospitalId = 2,
                            IsDeleted = false,
                            PatientId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            HospitalId = 2,
                            IsDeleted = false,
                            PatientId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 8,
                            HospitalId = 2,
                            IsDeleted = false,
                            PatientId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 9,
                            HospitalId = 2,
                            IsDeleted = false,
                            PatientId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2023, 1, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 10,
                            HospitalId = 2,
                            IsDeleted = false,
                            PatientId = 10
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchName = "Urology",
                            HospitalId = 1,
                            Name = "Sevket Can",
                            Password = "kalyancisevket",
                            PhoneNumber = "123456789",
                            Surname = "Kalyancioglu",
                            Username = "onlysevk"
                        },
                        new
                        {
                            Id = 2,
                            BranchName = "Cardiology",
                            HospitalId = 1,
                            Name = "John",
                            Password = "password",
                            PhoneNumber = "123456789",
                            Surname = "Doe",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 3,
                            BranchName = "Gynecology and Obstetrics",
                            HospitalId = 1,
                            Name = "Esmer",
                            Password = "hasanesmr",
                            PhoneNumber = "456123789",
                            Surname = "HASANOVA",
                            Username = "smerhasan"
                        },
                        new
                        {
                            Id = 4,
                            BranchName = "Brain surgery",
                            HospitalId = 1,
                            Name = "Sinem",
                            Password = "rivakkayariv",
                            PhoneNumber = "127834569",
                            Surname = "AKAY",
                            Username = "aksikinem"
                        },
                        new
                        {
                            Id = 5,
                            BranchName = "Psychiatry",
                            HospitalId = 1,
                            Name = "Faruk",
                            Password = "faruk3131",
                            PhoneNumber = "561278349",
                            Surname = "TUFEKCI",
                            Username = "hellokityfaruk"
                        },
                        new
                        {
                            Id = 6,
                            BranchName = "Internal Medicine Specialist",
                            HospitalId = 2,
                            Name = "Museyip",
                            Password = "muss03169",
                            PhoneNumber = "527613849",
                            Surname = "HAKKO",
                            Username = "museyipp"
                        },
                        new
                        {
                            Id = 7,
                            BranchName = "ENT Diseases Specialist",
                            HospitalId = 2,
                            Name = "Osman",
                            Password = "613127",
                            PhoneNumber = "561382749",
                            Surname = "Ozkeles",
                            Username = "usmankeles"
                        },
                        new
                        {
                            Id = 8,
                            BranchName = "Child Health and Diseases Specialist",
                            HospitalId = 2,
                            Name = "Cezmi",
                            Password = "8521613",
                            PhoneNumber = "527496138",
                            Surname = "Tuncer",
                            Username = "tuncercezmi"
                        },
                        new
                        {
                            Id = 9,
                            BranchName = "Eye Health and Diseases Specialist",
                            HospitalId = 2,
                            Name = "Zerrin",
                            Password = "631271",
                            PhoneNumber = "561749382",
                            Surname = "Goksin",
                            Username = "gokzerrin"
                        },
                        new
                        {
                            Id = 10,
                            BranchName = "Clinical Psychologist",
                            HospitalId = 2,
                            Name = "Leyla",
                            Password = "131267",
                            PhoneNumber = "527461389",
                            Surname = "Sonmez",
                            Username = "sonmezreis"
                        },
                        new
                        {
                            Id = 11,
                            BranchName = "Child Health and Diseases Specialist",
                            HospitalId = 3,
                            Name = "Denizmen",
                            Password = "131267",
                            PhoneNumber = "527461389",
                            Surname = "Aygün",
                            Username = "sonmezreis"
                        },
                        new
                        {
                            Id = 12,
                            BranchName = "Anesthesia and Reanimation",
                            HospitalId = 3,
                            Name = "Altay",
                            Password = "112367",
                            PhoneNumber = "574612389",
                            Surname = "Iskender",
                            Username = "sikender"
                        },
                        new
                        {
                            Id = 13,
                            BranchName = "Child Health and Diseases",
                            HospitalId = 3,
                            Name = "Alaattin",
                            Password = "167312",
                            PhoneNumber = "523874619",
                            Surname = "Ersoy",
                            Username = "ersoyyy"
                        },
                        new
                        {
                            Id = 14,
                            BranchName = "Nutrition and Diet",
                            HospitalId = 3,
                            Name = "Aleyna",
                            Password = "213167",
                            PhoneNumber = "538274619",
                            Surname = "Ergul",
                            Username = "ergulaleyna"
                        },
                        new
                        {
                            Id = 15,
                            BranchName = "Urologist",
                            HospitalId = 3,
                            Name = "Ali",
                            Password = "261317",
                            PhoneNumber = "513827469",
                            Surname = "Kadayifci",
                            Username = "alikadayifci"
                        },
                        new
                        {
                            Id = 16,
                            BranchName = "Gastroenterology",
                            HospitalId = 4,
                            Name = "Emre",
                            Password = "261731",
                            PhoneNumber = "518274369",
                            Surname = "YILDIRIM",
                            Username = "emreyildirim"
                        },
                        new
                        {
                            Id = 17,
                            BranchName = "Eye Diseases",
                            HospitalId = 4,
                            Name = "Abdullah",
                            Password = "231617",
                            PhoneNumber = "582137469",
                            Surname = "OZKAYA",
                            Username = "abdullahockaya"
                        },
                        new
                        {
                            Id = 18,
                            BranchName = "Urologist",
                            HospitalId = 4,
                            Name = "Abdulmuttalip",
                            Password = "276131",
                            PhoneNumber = "382751469",
                            Surname = "SIMSEK",
                            Username = "abulsimsek"
                        },
                        new
                        {
                            Id = 19,
                            BranchName = "Boys Urologist",
                            HospitalId = 4,
                            Name = "Abdurrahman",
                            Password = "261371",
                            PhoneNumber = "274695138",
                            Surname = "ONEN",
                            Username = "onenabd"
                        },
                        new
                        {
                            Id = 20,
                            BranchName = "Patology",
                            HospitalId = 4,
                            Name = "Furkan",
                            Password = "616161",
                            PhoneNumber = "5316678637",
                            Surname = "Keles",
                            Username = "kelesfurkan"
                        },
                        new
                        {
                            Id = 21,
                            BranchName = "Urologist",
                            HospitalId = 5,
                            Name = "Mete Oguz",
                            Password = "271361",
                            PhoneNumber = "138274659",
                            Surname = "Ekinci",
                            Username = "meteoguz"
                        },
                        new
                        {
                            Id = 22,
                            BranchName = "Ear Nose Throat Diseases",
                            HospitalId = 5,
                            Name = "Ekrem",
                            Password = "26117",
                            PhoneNumber = "513898927469",
                            Surname = "Aytac",
                            Username = "ekerrmm"
                        },
                        new
                        {
                            Id = 23,
                            BranchName = "General Surgery",
                            HospitalId = 5,
                            Name = "Ozer",
                            Password = "456875",
                            PhoneNumber = "51386527469",
                            Surname = "Celik",
                            Username = "ozercelik"
                        },
                        new
                        {
                            Id = 24,
                            BranchName = "Eye Health and Diseases",
                            HospitalId = 5,
                            Name = "Bahri",
                            Password = "26178317",
                            PhoneNumber = "51382437469",
                            Surname = "Muftuoglu",
                            Username = "bahri"
                        },
                        new
                        {
                            Id = 25,
                            BranchName = "Emergency room",
                            HospitalId = 5,
                            Name = "Mehmet",
                            Password = "26212341317",
                            PhoneNumber = "51382712469",
                            Surname = "Beyli",
                            Username = "memetbeyli"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 1,
                            Adress = "Kozyatağı, Kocayol Cd. No:19, 34742 Kadıköy/Istanbul",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Central Hospital",
                            Password = "centralPass",
                            PhoneNumber = "0216 4447799",
                            Username = "centralAdmin"
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 1,
                            Adress = "İdealtepe, Akgüvercin Sk. No:4, 34841 Maltepe/Istanbul",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Delta Hospital",
                            Password = "deltaPass",
                            PhoneNumber = "02163889999",
                            Username = "deltaAdmin"
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 1,
                            Adress = "Küçükyalı, Merkez Mh, Talat Bey Sok. No:28/B, 34840 Maltepe/Istanbul",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ibni Sina Hospital",
                            Password = "ibniPass",
                            PhoneNumber = "02165180900",
                            Username = "ibniAdmin"
                        },
                        new
                        {
                            Id = 4,
                            AdminId = 1,
                            Adress = "Cevizli, Talatpaşa Cd No:75, 34846 Maltepe/Istanbul",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Istanbul Onkoloji Hospital",
                            Password = "onkolojiPass",
                            PhoneNumber = "02164573737",
                            Username = "onkolojiAdmin"
                        },
                        new
                        {
                            Id = 5,
                            AdminId = 1,
                            Adress = "Altayçeşme, Varna Sk. No:16, 34843 Maltepe/Istanbul",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Maltepe Ersoy Hospital",
                            Password = "ersoyPass",
                            PhoneNumber = "085081186007",
                            Username = "ersoyAdmin"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Main Street 2",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "jane.smith1@example.com",
                            Name = "Jane",
                            Password = "password1",
                            PhoneNumber = "987654321",
                            Surname = "Smith",
                            TcNumber = "12345678901",
                            Username = "janesmith1"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Main Street 3",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "john.doe@example.com",
                            Name = "John",
                            Password = "password2",
                            PhoneNumber = "987654322",
                            Surname = "Doe",
                            TcNumber = "12345678902",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Main Street 4",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "alice.johnson@example.com",
                            Name = "Alice",
                            Password = "password3",
                            PhoneNumber = "987654323",
                            Surname = "Johnson",
                            TcNumber = "12345678903",
                            Username = "alicejohnson"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Main Street 5",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "bob.brown@example.com",
                            Name = "Bob",
                            Password = "password4",
                            PhoneNumber = "987654324",
                            Surname = "Brown",
                            TcNumber = "12345678904",
                            Username = "bobbrown"
                        },
                        new
                        {
                            Id = 5,
                            Adress = "Main Street 6",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "charlie.davis@example.com",
                            Name = "Charlie",
                            Password = "password5",
                            PhoneNumber = "987654325",
                            Surname = "Davis",
                            TcNumber = "12345678905",
                            Username = "charliedavis"
                        },
                        new
                        {
                            Id = 6,
                            Adress = "Main Street 7",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "david.wilson@example.com",
                            Name = "David",
                            Password = "password6",
                            PhoneNumber = "987654326",
                            Surname = "Wilson",
                            TcNumber = "12345678906",
                            Username = "davidwilson"
                        },
                        new
                        {
                            Id = 7,
                            Adress = "Main Street 8",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "emma.moore@example.com",
                            Name = "Emma",
                            Password = "password7",
                            PhoneNumber = "987654327",
                            Surname = "Moore",
                            TcNumber = "12345678907",
                            Username = "emmamoore"
                        },
                        new
                        {
                            Id = 8,
                            Adress = "Main Street 9",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "frank.taylor@example.com",
                            Name = "Frank",
                            Password = "password8",
                            PhoneNumber = "987654328",
                            Surname = "Taylor",
                            TcNumber = "12345678908",
                            Username = "franktaylor"
                        },
                        new
                        {
                            Id = 9,
                            Adress = "Main Street 10",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "grace.anderson@example.com",
                            Name = "Grace",
                            Password = "password9",
                            PhoneNumber = "987654329",
                            Surname = "Anderson",
                            TcNumber = "12345678909",
                            Username = "graceanderson"
                        },
                        new
                        {
                            Id = 10,
                            Adress = "Main Street 11",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "henry.thomas@example.com",
                            Name = "Henry",
                            Password = "password10",
                            PhoneNumber = "987654330",
                            Surname = "Thomas",
                            TcNumber = "12345678910",
                            Username = "henrythomas"
                        },
                        new
                        {
                            Id = 11,
                            Adress = "Main Street 12",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "ivy.jackson@example.com",
                            Name = "Ivy",
                            Password = "password11",
                            PhoneNumber = "987654331",
                            Surname = "Jackson",
                            TcNumber = "12345678911",
                            Username = "ivyjackson"
                        },
                        new
                        {
                            Id = 12,
                            Adress = "Main Street 13",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "jack.white@example.com",
                            Name = "Jack",
                            Password = "password12",
                            PhoneNumber = "987654332",
                            Surname = "White",
                            TcNumber = "12345678912",
                            Username = "jackwhite"
                        },
                        new
                        {
                            Id = 13,
                            Adress = "Main Street 14",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "kathy.harris@example.com",
                            Name = "Kathy",
                            Password = "password13",
                            PhoneNumber = "987654333",
                            Surname = "Harris",
                            TcNumber = "12345678913",
                            Username = "kathyharris"
                        },
                        new
                        {
                            Id = 14,
                            Adress = "Main Street 15",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "liam.martin@example.com",
                            Name = "Liam",
                            Password = "password14",
                            PhoneNumber = "987654334",
                            Surname = "Martin",
                            TcNumber = "12345678914",
                            Username = "liammartin"
                        },
                        new
                        {
                            Id = 15,
                            Adress = "Main Street 16",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "mia.lee@example.com",
                            Name = "Mia",
                            Password = "password15",
                            PhoneNumber = "987654335",
                            Surname = "Lee",
                            TcNumber = "12345678915",
                            Username = "mialee"
                        },
                        new
                        {
                            Id = 16,
                            Adress = "Main Street 17",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "nathan.clark@example.com",
                            Name = "Nathan",
                            Password = "password16",
                            PhoneNumber = "987654336",
                            Surname = "Clark",
                            TcNumber = "12345678916",
                            Username = "nathanclark"
                        },
                        new
                        {
                            Id = 17,
                            Adress = "Main Street 18",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "olivia.robinson@example.com",
                            Name = "Olivia",
                            Password = "password17",
                            PhoneNumber = "987654337",
                            Surname = "Robinson",
                            TcNumber = "12345678917",
                            Username = "oliviarobinson"
                        },
                        new
                        {
                            Id = 18,
                            Adress = "Main Street 19",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "paul.lewis@example.com",
                            Name = "Paul",
                            Password = "password18",
                            PhoneNumber = "987654338",
                            Surname = "Lewis",
                            TcNumber = "12345678918",
                            Username = "paullewis"
                        },
                        new
                        {
                            Id = 19,
                            Adress = "Main Street 20",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "quinn.walker@example.com",
                            Name = "Quinn",
                            Password = "password19",
                            PhoneNumber = "987654339",
                            Surname = "Walker",
                            TcNumber = "12345678919",
                            Username = "quinnwalker"
                        },
                        new
                        {
                            Id = 20,
                            Adress = "Main Street 21",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "rachel.hall@example.com",
                            Name = "Rachel",
                            Password = "password20",
                            PhoneNumber = "987654340",
                            Surname = "Hall",
                            TcNumber = "12345678920",
                            Username = "rachelhall"
                        },
                        new
                        {
                            Id = 21,
                            Adress = "Main Street 22",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "steve.young@example.com",
                            Name = "Steve",
                            Password = "password21",
                            PhoneNumber = "987654341",
                            Surname = "Young",
                            TcNumber = "12345678921",
                            Username = "steveyoung"
                        },
                        new
                        {
                            Id = 22,
                            Adress = "Main Street 23",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "tina.king@example.com",
                            Name = "Tina",
                            Password = "password22",
                            PhoneNumber = "987654342",
                            Surname = "King",
                            TcNumber = "12345678922",
                            Username = "tinaking"
                        },
                        new
                        {
                            Id = 23,
                            Adress = "Main Street 24",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "ursula.scott@example.com",
                            Name = "Ursula",
                            Password = "password23",
                            PhoneNumber = "987654343",
                            Surname = "Scott",
                            TcNumber = "12345678923",
                            Username = "ursulascott"
                        },
                        new
                        {
                            Id = 24,
                            Adress = "Main Street 25",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "victor.adams@example.com",
                            Name = "Victor",
                            Password = "password24",
                            PhoneNumber = "987654344",
                            Surname = "Adams",
                            TcNumber = "12345678924",
                            Username = "victoradams"
                        },
                        new
                        {
                            Id = 25,
                            Adress = "Main Street 26",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "wendy.evans@example.com",
                            Name = "Wendy",
                            Password = "password25",
                            PhoneNumber = "987654345",
                            Surname = "Evans",
                            TcNumber = "12345678925",
                            Username = "wendyevans"
                        },
                        new
                        {
                            Id = 26,
                            Adress = "Main Street 27",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "xavier.baker@example.com",
                            Name = "Xavier",
                            Password = "password26",
                            PhoneNumber = "987654346",
                            Surname = "Baker",
                            TcNumber = "12345678926",
                            Username = "xavierbaker"
                        },
                        new
                        {
                            Id = 27,
                            Adress = "Main Street 28",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "yara.parker@example.com",
                            Name = "Yara",
                            Password = "password27",
                            PhoneNumber = "987654347",
                            Surname = "Parker",
                            TcNumber = "12345678927",
                            Username = "yaraparker"
                        },
                        new
                        {
                            Id = 28,
                            Adress = "Main Street 29",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "zach.cook@example.com",
                            Name = "Zach",
                            Password = "password28",
                            PhoneNumber = "987654348",
                            Surname = "Cook",
                            TcNumber = "12345678928",
                            Username = "zachcook"
                        },
                        new
                        {
                            Id = 29,
                            Adress = "Main Street 30",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "adam.reed@example.com",
                            Name = "Adam",
                            Password = "password29",
                            PhoneNumber = "987654349",
                            Surname = "Reed",
                            TcNumber = "12345678929",
                            Username = "adamreed"
                        },
                        new
                        {
                            Id = 30,
                            Adress = "Main Street 31",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "bella.wright@example.com",
                            Name = "Bella",
                            Password = "password30",
                            PhoneNumber = "987654350",
                            Surname = "Wright",
                            TcNumber = "12345678930",
                            Username = "bellawright"
                        },
                        new
                        {
                            Id = 31,
                            Adress = "Main Street 32",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "chris.green@example.com",
                            Name = "Chris",
                            Password = "password31",
                            PhoneNumber = "987654351",
                            Surname = "Green",
                            TcNumber = "12345678931",
                            Username = "chrisgreen"
                        },
                        new
                        {
                            Id = 32,
                            Adress = "Main Street 33",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "diana.hill@example.com",
                            Name = "Diana",
                            Password = "password32",
                            PhoneNumber = "987654352",
                            Surname = "Hill",
                            TcNumber = "12345678932",
                            Username = "dianahill"
                        },
                        new
                        {
                            Id = 33,
                            Adress = "Main Street 34",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "ethan.scott@example.com",
                            Name = "Ethan",
                            Password = "password33",
                            PhoneNumber = "987654353",
                            Surname = "Scott",
                            TcNumber = "12345678933",
                            Username = "ethanscott"
                        },
                        new
                        {
                            Id = 34,
                            Adress = "Main Street 35",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "fiona.morris@example.com",
                            Name = "Fiona",
                            Password = "password34",
                            PhoneNumber = "987654354",
                            Surname = "Morris",
                            TcNumber = "12345678934",
                            Username = "fionamorris"
                        },
                        new
                        {
                            Id = 35,
                            Adress = "Main Street 36",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "george.cooper@example.com",
                            Name = "George",
                            Password = "password35",
                            PhoneNumber = "987654355",
                            Surname = "Cooper",
                            TcNumber = "12345678935",
                            Username = "georgecooper"
                        },
                        new
                        {
                            Id = 36,
                            Adress = "Main Street 37",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "hannah.nelson@example.com",
                            Name = "Hannah",
                            Password = "password36",
                            PhoneNumber = "987654356",
                            Surname = "Nelson",
                            TcNumber = "12345678936",
                            Username = "hannahnelson"
                        },
                        new
                        {
                            Id = 37,
                            Adress = "Main Street 38",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "ian.mitchell@example.com",
                            Name = "Ian",
                            Password = "password37",
                            PhoneNumber = "987654357",
                            Surname = "Mitchell",
                            TcNumber = "12345678937",
                            Username = "ianmitchell"
                        },
                        new
                        {
                            Id = 38,
                            Adress = "Main Street 39",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "jenna.perez@example.com",
                            Name = "Jenna",
                            Password = "password38",
                            PhoneNumber = "987654358",
                            Surname = "Perez",
                            TcNumber = "12345678938",
                            Username = "jennaperez"
                        },
                        new
                        {
                            Id = 39,
                            Adress = "Main Street 40",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "kyle.roberts@example.com",
                            Name = "Kyle",
                            Password = "password39",
                            PhoneNumber = "987654359",
                            Surname = "Roberts",
                            TcNumber = "12345678939",
                            Username = "kyleroberts"
                        },
                        new
                        {
                            Id = 40,
                            Adress = "Main Street 41",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "laura.phillips@example.com",
                            Name = "Laura",
                            Password = "password40",
                            PhoneNumber = "987654360",
                            Surname = "Phillips",
                            TcNumber = "12345678940",
                            Username = "lauraphillips"
                        },
                        new
                        {
                            Id = 41,
                            Adress = "Main Street 42",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "mark.campbell@example.com",
                            Name = "Mark",
                            Password = "password41",
                            PhoneNumber = "987654361",
                            Surname = "Campbell",
                            TcNumber = "12345678941",
                            Username = "markcampbell"
                        },
                        new
                        {
                            Id = 42,
                            Adress = "Main Street 43",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "nina.parker@example.com",
                            Name = "Nina",
                            Password = "password42",
                            PhoneNumber = "987654362",
                            Surname = "Parker",
                            TcNumber = "12345678942",
                            Username = "ninaparker"
                        },
                        new
                        {
                            Id = 43,
                            Adress = "Main Street 44",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "oscar.bennett@example.com",
                            Name = "Oscar",
                            Password = "password43",
                            PhoneNumber = "987654363",
                            Surname = "Bennett",
                            TcNumber = "12345678943",
                            Username = "oscarbennett"
                        },
                        new
                        {
                            Id = 44,
                            Adress = "Main Street 45",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "paula.carter@example.com",
                            Name = "Paula",
                            Password = "password44",
                            PhoneNumber = "987654364",
                            Surname = "Carter",
                            TcNumber = "12345678944",
                            Username = "paulacarter"
                        },
                        new
                        {
                            Id = 45,
                            Adress = "Main Street 46",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "quincy.morgan@example.com",
                            Name = "Quincy",
                            Password = "password45",
                            PhoneNumber = "987654365",
                            Surname = "Morgan",
                            TcNumber = "12345678945",
                            Username = "quincymorgan"
                        },
                        new
                        {
                            Id = 46,
                            Adress = "Main Street 47",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "rebecca.reed@example.com",
                            Name = "Rebecca",
                            Password = "password46",
                            PhoneNumber = "987654366",
                            Surname = "Reed",
                            TcNumber = "12345678946",
                            Username = "rebeccareed"
                        },
                        new
                        {
                            Id = 47,
                            Adress = "Main Street 48",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "samuel.ward@example.com",
                            Name = "Samuel",
                            Password = "password47",
                            PhoneNumber = "987654367",
                            Surname = "Ward",
                            TcNumber = "12345678947",
                            Username = "samuelward"
                        },
                        new
                        {
                            Id = 48,
                            Adress = "Main Street 49",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "tara.james@example.com",
                            Name = "Tara",
                            Password = "password48",
                            PhoneNumber = "987654368",
                            Surname = "James",
                            TcNumber = "12345678948",
                            Username = "tarajames"
                        },
                        new
                        {
                            Id = 49,
                            Adress = "Main Street 50",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "uma.henderson@example.com",
                            Name = "Uma",
                            Password = "password49",
                            PhoneNumber = "987654369",
                            Surname = "Henderson",
                            TcNumber = "12345678949",
                            Username = "umahenderson"
                        },
                        new
                        {
                            Id = 50,
                            Adress = "Main Street 51",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Mail = "violet.brooks@example.com",
                            Name = "Violet",
                            Password = "password50",
                            PhoneNumber = "987654370",
                            Surname = "Brooks",
                            TcNumber = "12345678950",
                            Username = "violetbrooks"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsDeleted = false,
                            MedicationName = "Aspirin",
                            PatientId = 1,
                            PrescriptionDate = new DateOnly(2023, 1, 1),
                            Usage = "Twice a day"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsDeleted = false,
                            MedicationName = "Ibuprofen",
                            PatientId = 2,
                            PrescriptionDate = new DateOnly(2023, 2, 15),
                            Usage = "Once a day"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsDeleted = false,
                            MedicationName = "Paracetamol",
                            PatientId = 3,
                            PrescriptionDate = new DateOnly(2023, 3, 10),
                            Usage = "Three times a day"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsDeleted = false,
                            MedicationName = "Metformin",
                            PatientId = 4,
                            PrescriptionDate = new DateOnly(2023, 4, 5),
                            Usage = "Twice a day"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsDeleted = false,
                            MedicationName = "Amoxicillin",
                            PatientId = 5,
                            PrescriptionDate = new DateOnly(2023, 5, 20),
                            Usage = "Once a day"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            IsDeleted = false,
                            MedicationName = "Atorvastatin",
                            PatientId = 6,
                            PrescriptionDate = new DateOnly(2023, 6, 25),
                            Usage = "Once a day"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            IsDeleted = false,
                            MedicationName = "Lisinopril",
                            PatientId = 7,
                            PrescriptionDate = new DateOnly(2023, 7, 30),
                            Usage = "Twice a day"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 8,
                            IsDeleted = false,
                            MedicationName = "Levothyroxine",
                            PatientId = 8,
                            PrescriptionDate = new DateOnly(2023, 8, 12),
                            Usage = "Once a day"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 9,
                            IsDeleted = false,
                            MedicationName = "Omeprazole",
                            PatientId = 9,
                            PrescriptionDate = new DateOnly(2023, 9, 18),
                            Usage = "Once a day"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 10,
                            IsDeleted = false,
                            MedicationName = "Simvastatin",
                            PatientId = 10,
                            PrescriptionDate = new DateOnly(2023, 10, 22),
                            Usage = "Twice a day"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Entity.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Entity.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital_Management_System.Entity.Entities.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Hospital", b =>
                {
                    b.HasOne("Hospital_Management_System.Entity.Entities.Admin", "Admin")
                        .WithMany("Hospitals")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Prescription", b =>
                {
                    b.HasOne("Hospital_Management_System.Entity.Entities.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Entity.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hospital_Management_System.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Admin", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Hospital_Management_System.Entity.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
